### ISSUE TITLE
For which OS version is this?

### ISSUE THREAD

**Issue by axlhazarika** [dotslashlevi/macosdebloater#1]
Nice attempt. For which OS version is this? Not working on Big Sur

**Comment by dotslashlevi** [comment]
Big Sur and Catalina have changed more services and daemons than previous versions. Also there is the fact that Big Sur and Catalina do not use the bash shell in which this is coded in. They use the ZSH shell. It is pretty much a whole new coding language but I will make a version for Big Sur and Catalina.
I do know that Mojave and backwards do work, as I have multiple iMacs both new and old.

**Comment by dotslashlevi** [comment]
So no, it WILL NOT work in macOS Big Sur or Catalina.

**Comment by dotslashlevi** [comment]
Oh and one more thing. You need something called System Integrity Protection turned off, which renders this script useless if its on, and it is on by default. So if you don't know what it is then its probably on.
